In [1]:
import numpy as np

In [2]:
np.random.randn(1,3)

array([[-1.33143368, -1.80013699, -1.49522153]])

In [3]:
np.random.randn(2,3) #2D array

array([[-0.17649765, -0.08604769,  0.59498745],
       [ 1.00114411,  0.92487431,  0.24503601]])

In [4]:
a = np.random.randn(2,3) * 10
a

array([[-0.13896849, -7.19621657, 16.78420094],
       [25.77515369, 16.57855032, 18.57268009]])

In [5]:
b = np.random.randn(2,3) #3D array
b

array([[-1.8183788 ,  0.46094714,  0.2105863 ],
       [-1.24377489,  0.42407177, -0.31454242]])

In [6]:
np.random.randn()

-1.01594630463425

In [7]:
a + b

array([[-1.95734729, -6.73526944, 16.99478724],
       [24.53137881, 17.00262209, 18.25813766]])

In [8]:
a.dtype

dtype('float64')

In [19]:
d = np.zeros(10)
d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
d.ndim

1

In [18]:
e = np.zeros((3,6))
e

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
e.dtype   #As default data type is float64, thats why weget points after each zero

dtype('float64')

In [13]:
np.empty((2, 3, 2))

array([[[7.88219538e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 3.69776220e-062]],

       [[4.95724439e-090, 2.35865790e+184],
        [1.53393260e-052, 1.09343102e-042],
        [3.99910963e+252, 8.34402697e-309]]])

In [14]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros_like(a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.full(fill_value = 5, shape=(2,3))

array([[5, 5, 5],
       [5, 5, 5]])

In [17]:
np.array(['sanju', 'the'], dtype= 'string_')

array([b'sanju', b'the'], dtype='|S5')